---
name: ast
version: '2.4'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: e67a6cc67c144e13e3d7a3e2e299f81f0a4e1778
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
